services:
  ssh-server:
    build: ./
    volumes:
      - ./ssh-shared/entrypoint.sh:/entrypoint.sh:ro
      - ./ssh-shared/etc/sshd_config:/etc/ssh/sshd_config:ro
      - ./ssh-shared/etc:/root/external:rw  # we can't mount pass-files directly
      - ./ssh-shared/home:/home:rw
    ports:
      - 0.0.0.0:443:443
    restart: on-failure:3
    entrypoint: 'sh /entrypoint.sh'
    command: '-e'  # logs to output (but file-logs is better for fail2ban scan)

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    volumes:
      - ./mtproto-shared:/data:rw
    ports:
      - 0.0.0.0:8443:443   # proxy port
      # - 0.0.0.0:12398:2398  # for /stats -- available only from localhost
    restart: on-failure:3
    stop_signal: SIGKILL
