services:
  ssh-server:
    build: ./
    volumes:
      - ./ssh-shared/entrypoint.sh:/entrypoint.sh:ro
      - ./ssh-shared/etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
      - ./ssh-shared/etc:/root/external-etc:rw  # we can't mount pass-files directly
      - ./ssh-shared/home:/home:rw
    ports:
      - 0.0.0.0:443:443
    restart: on-failure:3
    entrypoint: 'sh /entrypoint.sh'
    command: '-e'  # logs to output (but file-logs is better for fail2ban scan)

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    volumes:
      - ./mtproto-shared:/data:rw
    environment:
      TAG: ${MTPROTO_TAG:-}
      SECRET: ${MTPROTO_SECRET:-}  # for mtg-version use 'dd'-prefix to turn on obfuscation mode
    ports:
      - 0.0.0.0:8443:443  # proxy port (:2398/stats only from localhost)
    restart: on-failure:3
    stop_signal: SIGKILL
    # to support :2398 stats port uncomment next lines:
    # entrypoint: [ "/bin/sh", "-c" ]
    # command: "sed -i '/^exec.*\\/mtproto-proxy/{/$$@/!s/$/ \"$$@\"/}' /run.sh; /run.sh --http-stats"
