services:
  pac-server:
    image: busybox:stable-musl
    environment:
      DPI_PROXY_COMMAND: "${DPI_PROXY_COMMAND:-PROXY 127.0.0.1:8888}"
      EXT_PROXY_COMMAND: "${EXT_PROXY_COMMAND:-PROXY 127.0.0.1:3128}"
    volumes:
      - ./scripts:/opt/adp:ro
      - ./conf:/opt/adp-conf:ro
    ports:
      - 127.0.0.1:8082:8082
    stop_signal: SIGKILL
    entrypoint: 'sh /opt/adp/pac-server.sh -vv'

  dns-proxy:
    image: adguard/dnsproxy:latest
    volumes:
      - ./scripts:/opt/adp:ro
      - ./conf:/opt/adp-conf:ro
    environment:
      BOOTSTRAP_DNS: "9.9.9.9:53"
      DNS_FOR_PROXIED_DOMAINS: "https://dns9.quad9.net/dns-query"
      DEFAULT_DNS: "127.0.0.11"  # docker
    ports:
      - 127.0.0.1:53:53/tcp  # DNS
      - 127.0.0.1:53:53/udp  # DNS
      - 127.0.0.1:853:853/tcp  # DOT
    entrypoint: 'sh /opt/adp/dnsproxy.sh --verbose'

  ext-proxy:
    build: ./src/proxy-chain/
    volumes:
      - ./scripts:/opt/adp:ro
      - ./conf:/opt/adp-conf:ro
    depends_on:
      - dns-proxy
    ports:
      - 127.0.0.1:3128:3128
    entrypoint: 'sh /opt/adp/proxy-chain.sh'
    command: '--whitelist_file domains_for_ext_proxy.txt --verbose'

  # tor-proxy:
  #   image: peterdavehello/tor-socks-proxy:latest

  ssh-proxy:
    build: ./src/ssh-proxy/
    volumes:
      - ./scripts:/opt/adp:ro
      - ./conf:/opt/adp-conf:ro
    ports:
      - 127.0.0.1:1081:1081
    restart: on-failure:256  # if not setuped it will exit 0 => only on failures
    entrypoint: 'sh /opt/adp/ssh-proxy.sh'
    command: '-v'

  adpi-http-proxy:
    build: ./src/spoof_dpi/
    volumes:
      - ./scripts:/opt/adp:ro
      - ./conf:/opt/adp-conf:ro
      - ./conf/spoofdpi.toml:/etc/spoofdpi.toml:ro
    depends_on:
      - dns-proxy
      - ext-proxy
    ports:
      - 127.0.0.1:8888:8888
    environment:
      HTTP_PROXY: "http://ext-proxy:3129"
      HTTPS_PROXY: "http://ext-proxy:3129"
      NO_PROXY: "localhost,127.0.0.1"
    entrypoint: 'sh /opt/adp/spoofdpi.sh'
    command: '${SPOOF_DPI_COMMAND:---https-disorder --https-split-mode chunk --https-chunk-size 3} --log-level trace'

  # test-http-proxy:
  #   build: ./demergi/
  #   ports:
  #     - 127.0.0.1:8888:8888
  #   command: '--addrs 0.0.0.0:8888 --dns-mode dot --dot-server 9.9.9.9 --log-level debug --https-clienthello-size 10'

  adpi-socks5-proxy:
    # image: tazihad/byedpi
    build: ./src/bye_dpi/
    volumes:
      - ./conf:/opt/adp-conf:ro
      - ./scripts:/opt/adp:ro
    depends_on:
      - dns-proxy
      - ext-proxy
    ports:
      - 127.0.0.1:1080:1080
    environment:
      HTTP_PROXY: "http://ext-proxy:3129"
      HTTPS_PROXY: "http://ext-proxy:3129"
      NO_PROXY: "localhost,127.0.0.1"
    entrypoint: 'sh /opt/adp/bye_dpi.sh'
    # network_mode: "service:dns-proxy"  # join with dns-proxy to has overwritten DNS
    command: '${BYE_DPI_COMMAND:--o1 -a1 -At,r,s -d1 -a1} --debug 1'

networks:
  frontend:
    name: dns_proxy_network
    driver: custom-driver-1
