services:
  ssh-server:
    build: ./ssh-server/
    volumes:
      - ./ssh-server/shared/entrypoint.sh:/entrypoint.sh:ro
      - ./ssh-server/shared/etc/ssh/sshd_config:/etc/ssh/sshd_config:ro
      - ./ssh-server/shared/etc:/root/external-etc:rw  # we can't mount pass-files directly
      - ./ssh-server/shared/home:/home:rw
    ports:
      - 0.0.0.0:443:443
    restart: on-failure:3
    entrypoint: 'sh /entrypoint.sh'
    command: '-e'  # logs to output (but file-logs is better for fail2ban scan)

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    volumes:
      - ./mtproto-proxy:/data:rw
    environment:
      TAG: ${MTPROTO_TAG:-}
      SECRET: ${MTPROTO_SECRET:-}  # for mtg-version use 'dd'-prefix to turn on obfuscation mode
    ports:
      - 0.0.0.0:8443:443  # proxy port (:2398/stats only from localhost)
    restart: on-failure:3
    stop_signal: SIGKILL
    # to support :2398 stats port uncomment next lines:
    # entrypoint: [ "/bin/sh", "-c" ]
    # command: "sed -i '/^exec.*\\/mtproto-proxy/{/$$@/!s/$/ \"$$@\"/}' /run.sh; /run.sh --http-stats"

  telemt-proxy:
    image: ghcr.io/telemt/telemt:latest
    volumes:
      - ./telemt-proxy/config.toml:/app/config.toml:ro
    tmpfs:
      - /run/telemt:rw,mode=1777,size=1m
    environment:
      RUST_LOG: normal
    ports:
      - 0.0.0.0:4430:443
      - 127.0.0.1:9090:9090  # metrics:> curl -s localhost:9090/metrics | grep '^telemt_user_'
    restart: on-failure:3
    stop_signal: SIGKILL

  mtg-proxy:  # supports only FakeTLS mode (ee-secret)
    image: nineseconds/mtg:2
    volumes:
      - ./mtg-proxy/config.toml:/config/config.toml:ro
    ports:
      - 0.0.0.0:4431:3128
      # - 127.0.0.1:9091:3129  # stats:> curl -s localhost:9091 | grep '^mtg_domain_fronting'
    restart: on-failure:3

  # test VPN
  # amnesiawg:
  #   build: ./amnesiawg
  #   # volumes:
  #   #   - /opt/amneziawg:/etc/amnezia:rw
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   cap_add:
  #     - NET_ADMIN
  #   ports:
  #     # - 0.0.0.0:44344:51820/udp
  #     - 0.0.0.0:44344:58083/udp
  #   restart: on-failure:3
