services:
  ssh-server:
    build: ./
    volumes:
      - ./container/entrypoint.sh:/entrypoint.sh:ro
      - ./container/etc/sshd_config:/etc/ssh/sshd_config:ro
      - ./container/etc:/root/external:rw  # we can't mount pass-files directly
      - ./container/home:/home:rw
    ports:
      - 0.0.0.0:443:443
    entrypoint: '/entrypoint.sh'
    command: '-e'  # logs to output (but file-logs is better for fail2ban scan)

  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    volumes:
      - ./mtproto-shared:/data:rw
    ports:
      - 127.0.0.1:8443:443   # proxy port
      - 127.0.0.1:12398:2398  # for /stats
